---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - esphome
  - frigate
  - frigate-test
  - home-assistant
  - mqtt
  - node-red
  - appdaemon
  - frigate-dad
  - home-assistant-dad
  - teslamate
  - daily-restart.yaml
  - evcc
  - tesla-command-proxy
  - signtools
  - amber2mqtt
